### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kevindeyne** [kevindeyne/papertrace#1]
- [ ] Store OCR and image in IndexedDB (see [link](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API))
- [ ] Ability to remove data
- [ ] Basic search functionality (start with matching OCR data -> filter images)
- [ ] Fuzzy search
- [ ] Language for OCR
- [ ] Progress indicators
- [ ] Upscale image?
- [ ] Categorize images
- [ ] Extract/interpret relevant info such as dates
